version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3111:3111"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - ./manufacturer.db:/app/manufacturer.db
